pluginManagement {
    repositories {
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        maven {
            name = 'TencentMirror'
            url = 'https://mirrors.cloud.tencent.com/nexus/repository/maven-public/'
        }
        mavenCentral()
        gradlePluginPortal()
    }
}

rootProject.name = 'customsplash'
